import { CarListing } from "../Types/listing.type";
import { Company } from "../Types/company.type";

export const mockList: CarListing[] = [
    {
        id: 1,
        make: "BMW",
        type: "A-class",
        price: 22000,
        image:"Images/Cars/Bmw.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 2,
        make: "Ford",
        type: "Focus",
        price: 9500,
        image:"Images/Cars/ford.png",
        horsepower: 100,
        engine: "petrol",
    },
    {
        id: 3,
        make: "Mercedes",
        type: "Benz-55",
        price: 13500,
        image:"Images/Cars/mercedes.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 4,
        make: "Opel",
        type: "Corsa",
        price: 8000,
        image:"Images/Cars/opel.png",
        horsepower: 115,
        engine: "diesel",
    },
    {
        id: 5,
        make: "Volkswagen",
        type: "Polo",
        price: 15100,
        image:"Images/Cars/volkswagen.png",
        horsepower: 120,
        engine: "diesel",
    },
    {
        id: 6,
        make: "BMW",
        type: "A-class",
        price: 22300,
        image:"Images/Cars/Bmw.png",
        horsepower: 120,
        engine: "diesel",
    },
    {
        id: 7,
        make: "Ford",
        type: "Focus",
        price: 7340,
        image:"Images/Cars/ford.png",
        horsepower: 130,
        engine: "petrol",
    },
    {
        id: 8,
        make: "Mercedes",
        type: "Benz-55",
        price: 11500,
        image:"Images/Cars/mercedes.png",
        horsepower: 110,
        engine: "diesel",
    },
    {
        id: 9,
        make: "Opel",
        type: "Corsa",
        price: 9200,
        image:"Images/Cars/opel.png",
        horsepower: 130,
        engine: "petrol",
    },
    {
        id: 10,
        make: "Volkswagen",
        type: "Polo",
        price: 17300,
        image:"Images/Cars/volkswagen.png",
        horsepower: 120,
        engine: "petrol",
    },
    {
        id: 11,
        make: "BMW",
        type: "A-class",
        price: 19200,
        image:"Images/Cars/Bmw.png",
        horsepower: 125,
        engine: "petrol",
    },
    {
        id: 12,
        make: "Ford",
        type: "Focus",
        price: 18100,
        image:"Images/Cars/ford.png",
        horsepower: 125,
        engine: "diesel",
    },
    {
        id: 13,
        make: "Mercedes",
        type: "Benz-55",
        price: 11350,
        image:"Images/Cars/mercedes.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 14,
        make: "Opel",
        type: "Corsa",
        price: 8750,
        image:"Images/Cars/opel.png",
        horsepower: 125,
        engine: "petrol",
    },
    {
        id: 15,
        make: "Volkswagen",
        type: "Polo",
        price: 1750,
        image:"Images/Cars/volkswagen.png",
        horsepower: 130,
        engine: "diesel",
    },
    {
        id: 16,
        make: "BMW",
        type: "A-class",
        price: 3450,
        image:"Images/Cars/Bmw.png",
        horsepower: 100,
        engine: "diesel",
    },
    {
        id: 17,
        make: "Ford",
        type: "Focus",
        price: 7700,
        image:"Images/Cars/ford.png",
        horsepower: 100,
        engine: "diesel",
    },
    {
        id: 18,
        make: "Mercedes",
        type: "Benz-55",
        price: 16400,
        image:"Images/Cars/mercedes.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 19,
        make: "Opel",
        type: "Corsa",
        price: 9900,
        image:"Images/Cars/opel.png",
        horsepower: 125,
        engine: "petrol",
    },
    {
        id: 20,
        make: "Volkswagen",
        type: "Polo",
        price: 11100,
        image:"Images/Cars/volkswagen.png",
        horsepower: 130,
        engine: "petrol",
    },
    {
        id: 21,
        make: "Volkswagen",
        type: "Polo",
        price: 18340,
        image:"Images/Cars/volkswagen.png",
        horsepower: 125,
        engine: "diesel",
    },
    {
        id: 22,
        make: "BMW",
        type: "A-class",
        price: 20200,
        image:"Images/Cars/Bmw.png",
        horsepower: 110,
        engine: "diesel",
    },
    {
        id: 23,
        make: "Ford",
        type: "Focus",
        price: 19100,
        image:"Images/Cars/ford.png",
        horsepower: 105,
        engine: "petrol",
    },
    {
        id: 24,
        make: "Mercedes",
        type: "Benz-55",
        price: 13300,
        image:"Images/Cars/mercedes.png",
        horsepower: 140,
        engine: "petrol",
    },
    {
        id: 25,
        make: "Opel",
        type: "Corsa",
        price: 8120,
        image:"Images/Cars/opel.png",
        horsepower: 120,
        engine: "petrol",
    },
    {
        id: 26,
        make: "Volkswagen",
        type: "Polo",
        price: 15700,
        image:"Images/Cars/volkswagen.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 27,
        make: "Volkswagen",
        type: "Polo",
        price: 16200,
        image:"Images/Cars/volkswagen.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 28,
        make: "Volkswagen",
        type: "Polo",
        price: 13400,
        image:"Images/Cars/volkswagen.png",
        horsepower: 100,
        engine: "diesel",
    },
    {
        id: 29,
        make: "BMW",
        type: "A-class",
        price: 15900,
        image:"Images/Cars/Bmw.png",
        horsepower: 105,
        engine: "diesel",
    },
    {
        id: 30,
        make: "Ford",
        type: "Focus",
        price: 2350,
        image:"Images/Cars/ford.png",
        horsepower: 110,
        engine: "diesel",
    },
    {
        id: 31,
        make: "Mercedes",
        type: "Benz-55",
        price: 4400,
        image:"Images/Cars/mercedes.png",
        horsepower: 120,
        engine: "diesel",
    },
    {
        id: 32,
        make: "Opel",
        type: "Corsa",
        price: 9820,
        image:"Images/Cars/opel.png",
        horsepower: 120,
        engine: "diesel",
    },
    {
        id: 33,
        make: "Volkswagen",
        type: "Polo",
        price: 18340,
        image:"Images/Cars/volkswagen.png",
        horsepower: 110,
        engine: "diesel",
    },
    {
        id: 34,
        make: "BMW",
        type: "A-class",
        price: 22000,
        image:"Images/Cars/Bmw.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 35,
        make: "Ford",
        type: "Focus",
        price: 9500,
        image:"Images/Cars/ford.png",
        horsepower: 100,
        engine: "petrol",
    },
    {
        id: 36,
        make: "Mercedes",
        type: "Benz-55",
        price: 13500,
        image:"Images/Cars/mercedes.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 37,
        make: "Opel",
        type: "Corsa",
        price: 8000,
        image:"Images/Cars/opel.png",
        horsepower: 115,
        engine: "diesel",
    },
    {
        id: 38,
        make: "Volkswagen",
        type: "Polo",
        price: 15100,
        image:"Images/Cars/volkswagen.png",
        horsepower: 120,
        engine: "diesel",
    },
    {
        id: 39,
        make: "BMW",
        type: "A-class",
        price: 22300,
        image:"Images/Cars/Bmw.png",
        horsepower: 120,
        engine: "diesel",
    },
    {
        id: 40,
        make: "Ford",
        type: "Focus",
        price: 7340,
        image:"Images/Cars/ford.png",
        horsepower: 130,
        engine: "petrol",
    },
    {
        id: 41,
        make: "Mercedes",
        type: "Benz-55",
        price: 11500,
        image:"Images/Cars/mercedes.png",
        horsepower: 110,
        engine: "diesel",
    },
    {
        id: 42,
        make: "Opel",
        type: "Corsa",
        price: 9200,
        image:"Images/Cars/opel.png",
        horsepower: 130,
        engine: "petrol",
    },
    {
        id: 43,
        make: "Volkswagen",
        type: "Polo",
        price: 17300,
        image:"Images/Cars/volkswagen.png",
        horsepower: 120,
        engine: "petrol",
    },
    {
        id: 44,
        make: "BMW",
        type: "A-class",
        price: 19200,
        image:"Images/Cars/Bmw.png",
        horsepower: 125,
        engine: "petrol",
    },
    {
        id: 45,
        make: "Ford",
        type: "Focus",
        price: 18100,
        image:"Images/Cars/ford.png",
        horsepower: 125,
        engine: "diesel",
    },
    {
        id: 46,
        make: "Mercedes",
        type: "Benz-55",
        price: 11350,
        image:"Images/Cars/mercedes.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 47,
        make: "Opel",
        type: "Corsa",
        price: 8750,
        image:"Images/Cars/opel.png",
        horsepower: 125,
        engine: "petrol",
    },
    {
        id: 48,
        make: "Volkswagen",
        type: "Polo",
        price: 1750,
        image:"Images/Cars/volkswagen.png",
        horsepower: 130,
        engine: "diesel",
    },
    {
        id: 49,
        make: "BMW",
        type: "A-class",
        price: 3450,
        image:"Images/Cars/Bmw.png",
        horsepower: 100,
        engine: "diesel",
    },
    {
        id: 50,
        make: "Ford",
        type: "Focus",
        price: 7700,
        image:"Images/Cars/ford.png",
        horsepower: 100,
        engine: "diesel",
    },
    {
        id: 51,
        make: "Mercedes",
        type: "Benz-55",
        price: 16400,
        image:"Images/Cars/mercedes.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 52,
        make: "Opel",
        type: "Corsa",
        price: 9900,
        image:"Images/Cars/opel.png",
        horsepower: 125,
        engine: "petrol",
    },
    {
        id: 53,
        make: "Volkswagen",
        type: "Polo",
        price: 11100,
        image:"Images/Cars/volkswagen.png",
        horsepower: 130,
        engine: "petrol",
    },
    {
        id: 54,
        make: "Volkswagen",
        type: "Polo",
        price: 18340,
        image:"Images/Cars/volkswagen.png",
        horsepower: 125,
        engine: "diesel",
    },
    {
        id: 55,
        make: "BMW",
        type: "A-class",
        price: 20200,
        image:"Images/Cars/Bmw.png",
        horsepower: 110,
        engine: "diesel",
    },
    {
        id: 56,
        make: "Ford",
        type: "Focus",
        price: 19100,
        image:"Images/Cars/ford.png",
        horsepower: 105,
        engine: "petrol",
    },
    {
        id: 57,
        make: "Mercedes",
        type: "Benz-55",
        price: 13300,
        image:"Images/Cars/mercedes.png",
        horsepower: 140,
        engine: "petrol",
    },
    {
        id: 58,
        make: "Opel",
        type: "Corsa",
        price: 8120,
        image:"Images/Cars/opel.png",
        horsepower: 120,
        engine: "petrol",
    },
    {
        id: 59,
        make: "Volkswagen",
        type: "Polo",
        price: 15700,
        image:"Images/Cars/volkswagen.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 60,
        make: "Volkswagen",
        type: "Polo",
        price: 16200,
        image:"Images/Cars/volkswagen.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 61,
        make: "Volkswagen",
        type: "Polo",
        price: 13400,
        image:"Images/Cars/volkswagen.png",
        horsepower: 100,
        engine: "diesel",
    },
    {
        id: 62,
        make: "BMW",
        type: "A-class",
        price: 15900,
        image:"Images/Cars/Bmw.png",
        horsepower: 105,
        engine: "diesel",
    },
    {
        id: 63,
        make: "Ford",
        type: "Focus",
        price: 2350,
        image:"Images/Cars/ford.png",
        horsepower: 110,
        engine: "diesel",
    },
    {
        id: 64,
        make: "Mercedes",
        type: "Benz-55",
        price: 4400,
        image:"Images/Cars/mercedes.png",
        horsepower: 120,
        engine: "diesel",
    },
    {
        id: 65,
        make: "Opel",
        type: "Corsa",
        price: 9820,
        image:"Images/Cars/opel.png",
        horsepower: 120,
        engine: "diesel",
    },
    {
        id: 66,
        make: "Volkswagen",
        type: "Polo",
        price: 18340,
        image:"Images/Cars/volkswagen.png",
        horsepower: 110,
        engine: "diesel",
    },
    {
        id: 67,
        make: "BMW",
        type: "A-class",
        price: 22000,
        image:"Images/Cars/Bmw.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 68,
        make: "Ford",
        type: "Focus",
        price: 9500,
        image:"Images/Cars/ford.png",
        horsepower: 100,
        engine: "petrol",
    },
    {
        id: 69,
        make: "Mercedes",
        type: "Benz-55",
        price: 13500,
        image:"Images/Cars/mercedes.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 70,
        make: "Opel",
        type: "Corsa",
        price: 8000,
        image:"Images/Cars/opel.png",
        horsepower: 115,
        engine: "diesel",
    },
    {
        id: 71,
        make: "Volkswagen",
        type: "Polo",
        price: 15100,
        image:"Images/Cars/volkswagen.png",
        horsepower: 120,
        engine: "diesel",
    },
    {
        id: 72,
        make: "BMW",
        type: "A-class",
        price: 22300,
        image:"Images/Cars/Bmw.png",
        horsepower: 120,
        engine: "diesel",
    },
    {
        id: 73,
        make: "Ford",
        type: "Focus",
        price: 7340,
        image:"Images/Cars/ford.png",
        horsepower: 130,
        engine: "petrol",
    },
    {
        id: 74,
        make: "Mercedes",
        type: "Benz-55",
        price: 11500,
        image:"Images/Cars/mercedes.png",
        horsepower: 110,
        engine: "diesel",
    },
    {
        id: 75,
        make: "Opel",
        type: "Corsa",
        price: 9200,
        image:"Images/Cars/opel.png",
        horsepower: 130,
        engine: "petrol",
    },
    {
        id: 76,
        make: "Volkswagen",
        type: "Polo",
        price: 17300,
        image:"Images/Cars/volkswagen.png",
        horsepower: 120,
        engine: "petrol",
    },
    {
        id: 77,
        make: "BMW",
        type: "A-class",
        price: 19200,
        image:"Images/Cars/Bmw.png",
        horsepower: 125,
        engine: "petrol",
    },
    {
        id: 78,
        make: "Ford",
        type: "Focus",
        price: 18100,
        image:"Images/Cars/ford.png",
        horsepower: 125,
        engine: "diesel",
    },
    {
        id: 79,
        make: "Mercedes",
        type: "Benz-55",
        price: 11350,
        image:"Images/Cars/mercedes.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 80,
        make: "Opel",
        type: "Corsa",
        price: 8750,
        image:"Images/Cars/opel.png",
        horsepower: 125,
        engine: "petrol",
    },
    {
        id: 81,
        make: "Volkswagen",
        type: "Polo",
        price: 1750,
        image:"Images/Cars/volkswagen.png",
        horsepower: 130,
        engine: "diesel",
    },
    {
        id: 82,
        make: "BMW",
        type: "A-class",
        price: 3450,
        image:"Images/Cars/Bmw.png",
        horsepower: 100,
        engine: "diesel",
    },
    {
        id: 83,
        make: "Ford",
        type: "Focus",
        price: 7700,
        image:"Images/Cars/ford.png",
        horsepower: 100,
        engine: "diesel",
    },
    {
        id: 84,
        make: "Mercedes",
        type: "Benz-55",
        price: 16400,
        image:"Images/Cars/mercedes.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 85,
        make: "Opel",
        type: "Corsa",
        price: 9900,
        image:"Images/Cars/opel.png",
        horsepower: 125,
        engine: "petrol",
    },
    {
        id: 86,
        make: "Volkswagen",
        type: "Polo",
        price: 11100,
        image:"Images/Cars/volkswagen.png",
        horsepower: 130,
        engine: "petrol",
    },
    {
        id: 87,
        make: "Volkswagen",
        type: "Polo",
        price: 18340,
        image:"Images/Cars/volkswagen.png",
        horsepower: 125,
        engine: "diesel",
    },
    {
        id: 88,
        make: "BMW",
        type: "A-class",
        price: 20200,
        image:"Images/Cars/Bmw.png",
        horsepower: 110,
        engine: "diesel",
    },
    {
        id: 89,
        make: "Ford",
        type: "Focus",
        price: 19100,
        image:"Images/Cars/ford.png",
        horsepower: 105,
        engine: "petrol",
    },
    {
        id: 90,
        make: "Mercedes",
        type: "Benz-55",
        price: 13300,
        image:"Images/Cars/mercedes.png",
        horsepower: 140,
        engine: "petrol",
    },
    {
        id: 91,
        make: "Opel",
        type: "Corsa",
        price: 8120,
        image:"Images/Cars/opel.png",
        horsepower: 120,
        engine: "petrol",
    },
    {
        id: 92,
        make: "Volkswagen",
        type: "Polo",
        price: 15700,
        image:"Images/Cars/volkswagen.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 93,
        make: "Volkswagen",
        type: "Polo",
        price: 16200,
        image:"Images/Cars/volkswagen.png",
        horsepower: 110,
        engine: "petrol",
    },
    {
        id: 94,
        make: "Volkswagen",
        type: "Polo",
        price: 13400,
        image:"Images/Cars/volkswagen.png",
        horsepower: 100,
        engine: "diesel",
    },
    {
        id: 95,
        make: "BMW",
        type: "A-class",
        price: 15900,
        image:"Images/Cars/Bmw.png",
        horsepower: 105,
        engine: "diesel",
    },
    {
        id: 96,
        make: "Ford",
        type: "Focus",
        price: 2350,
        image:"Images/Cars/ford.png",
        horsepower: 110,
        engine: "diesel",
    },
    {
        id: 97,
        make: "Mercedes",
        type: "Benz-55",
        price: 4400,
        image:"Images/Cars/mercedes.png",
        horsepower: 120,
        engine: "diesel",
    },
    {
        id: 98,
        make: "Opel",
        type: "Corsa",
        price: 9820,
        image:"Images/Cars/opel.png",
        horsepower: 120,
        engine: "diesel",
    },
    {
        id: 99,
        make: "Volkswagen",
        type: "Polo",
        price: 18340,
        image:"Images/Cars/volkswagen.png",
        horsepower: 110,
        engine: "diesel",
    },
]

export const companyList: Company[] = [
    {
        id:1,
        company: "BMW",
    },
    {
        id:2,
        company: "Ford",
    },
    {
        id:3,
        company: "Mercedes",
    },
    {
        id:4,
        company: "Volkswagen",
    },
    {
        id:5,
        company: "Opel",
    },
]